project_id = "zghqhmecbzuaesaspqgr"

[functions.validate-image]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-reset-code]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.check-expiring-subscriptions]
verify_jwt = false
