export type AndroidReleaseChangeType = "feature" | "improvement" | "fix";

export type AndroidReleaseChange = {
  type: AndroidReleaseChangeType;
  text: string;
};

export const androidRelease = {
  version: "0.1.62",
  build: 62,
  releasedAt: "2026-09-14",
  changes: [
    { type: "feature", text: "Aviso de nova versão dentro do app, com comparação automática da build instalada e download direto da APK Android." },
    { type: "improvement", text: "Ícone de atualização ao lado do badge MaisCtrl, com modal central para detalhes e download da APK." },
    { type: "feature", text: "Hub **Mais** no menu inferior, reunindo cartões, financiamentos, empréstimos, metas, tarefas, relatórios, Ctrl AI, +Couple, +Share e Premium." },
    { type: "feature", text: "Módulos locais para cartões e faturas, compromissos de crédito, metas, tarefas e assinaturas compartilhadas, com persistência no aparelho e suporte básico offline." },
    { type: "feature", text: "Relatório resumido com exportação CSV e área reservada para exportações Premium em Excel/PDF." },
    { type: "feature", text: "Ctrl AI local com respostas orientativas e limite de cinco perguntas no plano Free." },
    { type: "feature", text: "Tela de Premium com planos mensal/anual, teste de sete dias, contratação por cartão e indicação clara quando o checkout seguro ainda precisa ser conectado." },
    { type: "feature", text: "Área +Couple com código de convite e área +Share com divisão automática 50/50 e status de pagamento." },
    { type: "feature", text: "Importação local de extratos bancários e de cartão em OFX/QFX, com prévia, confirmação e prevenção de lançamentos duplicados." },
    { type: "improvement", text: "Atualização Android agora concede seis horas de tolerância após a primeira detecção e bloqueia o app até a instalação da versão mais recente depois do prazo." },
    { type: "improvement", text: "Ícone do app atualizado com a imagem oficial enviada, com fundo preto, no Android, iOS e versão web instalável." },
    { type: "improvement", text: "Tela de cartões ganhou representações visuais por instituição, com logo/nome, final do cartão, fechamento e vencimento." },
    { type: "improvement", text: "Resumo de cada cartão agora exibe fatura, saldo disponível, limite e percentual usado; múltiplos cartões podem ser explorados por deslize horizontal." },
    { type: "improvement", text: "Direção visual do dashboard aplicada com tokens inspirados no Material 3, superfícies tonais e estados de interação mais consistentes." },
    { type: "improvement", text: "Resumo financeiro reorganizado em bento grid responsivo, com saldo em destaque e métricas agrupadas por contexto." },
    { type: "improvement", text: "Telas de módulos, cartões, calendário, relatórios e menu Mais ganharam hierarquia de superfícies e cantos expressivos, sem gradientes." },
    { type: "improvement", text: "Catálogo de logos via CDN ampliado para bancos, academias, operadoras, delivery e outros serviços, com fallback por domínio e pela inicial." },
    { type: "improvement", text: "Campos de data dos módulos locais padronizados para `dd/mm/aaaa`, com calendário opcional e leitura consistente em pt-BR." },
    { type: "improvement", text: "Superfícies do app agora usam cores sólidas, bordas e sombras para uma leitura mais limpa, sem gradientes decorativos." },
    { type: "improvement", text: "Modal de detalhes de assinatura refinado com identidade visual, resumo bento e ações com hierarquia mais clara." },
    { type: "improvement", text: "Home do dashboard reorganizada em uma composição bento, com saldo âncora, métricas assimétricas e blocos de atenção com identidades visuais diferentes." },
    { type: "improvement", text: "Hub **Mais** redesenhado como uma grade de tiles bento coloridos, com destaque para áreas Premium e suporte a mais itens sem cortar o conteúdo." },
    { type: "improvement", text: "Resumos dos módulos ganharam superfícies próprias — lilás, azul, coral, rosa e verde — para diferenciar contexto e prioridade." },
    { type: "improvement", text: "Logo decorativa removida da tela de cadastro para deixar o formulário livre acima do teclado." },
    { type: "improvement", text: "Badge da logo MaisCtrl no painel pessoal transformado em entrada para o espaço +2." },
    { type: "improvement", text: "Nova tela fixa do +2 criada com identidade visual própria e retorno direto para o painel pessoal." },
    { type: "improvement", text: "Cadastro de assinaturas reorganizado em um fluxo modal de três etapas, com revisão antes de salvar." },
    { type: "improvement", text: "Badge principal renomeado para MaisCtrl e espaço do casal identificado como +Couple após o clique." },
    { type: "improvement", text: "Avatar do perfil exibido no botão do cabeçalho, ao lado das notificações." },
    { type: "improvement", text: "Menu inferior redesenhado como dock flutuante, com aba ativa destacada e respiro para a área segura do aparelho." },
    { type: "improvement", text: "Perfil removido do menu inferior; o acesso continua disponível pelo avatar no cabeçalho." },
    { type: "improvement", text: "Logos de marcas conhecidas adicionadas às assinaturas via CDN público, com fallback para a inicial." },
    { type: "improvement", text: "Ícone adaptativo do Android alinhado à logo oficial enviada, removendo o foreground padrão do template." },
    { type: "improvement", text: "Lançamentos importados identificados pela conta e pelo `FITID` do banco para manter o histórico seguro em novas importações." },
    { type: "fix", text: "Formulários locais revisados para manter contraste, foco visível, conteúdo acessível e teclado oculto ao fechar um modal." },
    { type: "fix", text: "Telas empilhadas inativas deixaram de aparecer para leitores de tela durante as transições." },
    { type: "fix", text: "Tela inicial de autenticação mantida fixa, sem rolagem ou deslocamento do card de ações." },
    { type: "fix", text: "Campos de login reposicionados automaticamente para permanecerem visíveis acima do teclado." },
    { type: "fix", text: "Tela de cadastro mantida estática, sem rolagem, com o formulário acima do teclado." },
    { type: "fix", text: "Teclado simulado expandido até as laterais da tela, sem falhas nos cantos superiores." },
    { type: "fix", text: "Upload de foto de perfil habilitado no Supabase com bucket e políticas de acesso por usuário." },
    { type: "fix", text: "Formulários em bottom sheet mantidos fixos, com espaço de segurança acima do teclado." },
    { type: "fix", text: "Link de recuperação de senha passou a abrir o formulário de nova senha dentro do app." },
    { type: "fix", text: "Callback de recuperação separado do login normal para impedir entrada direta no painel sem trocar a senha." },
    { type: "fix", text: "Deep link `maisctrl://auth/callback` registrado também no iOS para completar a recuperação de senha." },
  ],
} as const;
